build_image:
  image: docker:git
  services:
    - docker:dind
  script:
    - docker pull wise2c/playbook:v1.20
    - docker pull wise2c/playbook:v1.19
    - docker pull wise2c/playbook:v1.18
    - docker pull wise2c/playbook:v1.17
    - docker tag wise2c/playbook:v1.20 wise2c/playbook:v1.20.1
    - docker tag wise2c/playbook:v1.19 wise2c/playbook:v1.19.6
    - docker tag wise2c/playbook:v1.18 wise2c/playbook:v1.18.14
    - docker tag wise2c/playbook:v1.17 wise2c/playbook:v1.17.16
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD registry.cn-shenzhen.aliyuncs.com
    - docker push wise2c/playbook:v1.20.1
    - docker push wise2c/playbook:v1.19.6
    - docker push wise2c/playbook:v1.18.14
    - docker push wise2c/playbook:v1.17.16

    - docker pull wise2c/yum-repo:v1.20.1
    - docker pull wise2c/yum-repo:v1.19.6
    - docker pull wise2c/yum-repo:v1.18.14
    - docker pull wise2c/yum-repo:v1.17.16
    - docker tag wise2c/yum-repo:v1.20.1 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.20.1
    - docker tag wise2c/yum-repo:v1.19.6 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.19.6
    - docker tag wise2c/yum-repo:v1.18.14 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.14
    - docker tag wise2c/yum-repo:v1.17.16 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.16
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.20.1
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.19.6
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.14
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.16

    - docker pull wise2c/apt-source:v1.20.1
    - docker pull wise2c/apt-source:v1.19.6
    - docker pull wise2c/apt-source:v1.18.14
    - docker pull wise2c/apt-source:v1.17.16
    - docker tag wise2c/apt-source:v1.20.1 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.20.1
    - docker tag wise2c/apt-source:v1.19.6 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.19.6
    - docker tag wise2c/apt-source:v1.18.14 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.14
    - docker tag wise2c/apt-source:v1.17.16 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.16
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.20.1
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.19.6
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.14
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.16

    - docker pull wise2c/playbook:v1.20.1
    - docker pull wise2c/playbook:v1.19.6
    - docker pull wise2c/playbook:v1.18.14
    - docker pull wise2c/playbook:v1.17.16
    - docker tag wise2c/playbook:v1.20.1 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.20.1
    - docker tag wise2c/playbook:v1.19.6 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.19.6
    - docker tag wise2c/playbook:v1.18.14 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.14
    - docker tag wise2c/playbook:v1.17.16 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.16
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.20.1
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.19.6
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.14
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.16
  when: always
