build_image:
  image: docker:git
  services:
    - docker:dind
  script:
    - docker pull wise2c/playbook:v1.20.4
    - docker pull wise2c/playbook:v1.19.8
    - docker pull wise2c/playbook:v1.18.16
    - docker tag wise2c/playbook:v1.20.4 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.20.4
    - docker tag wise2c/playbook:v1.19.8 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.19.8
    - docker tag wise2c/playbook:v1.18.16 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.16
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.20.4
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.19.8
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.16
    
    - docker pull wise2c/yum-repo:v1.20.4
    - docker pull wise2c/yum-repo:v1.19.8
    - docker pull wise2c/yum-repo:v1.18.16
    - docker tag wise2c/yum-repo:v1.20.4 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.20.4
    - docker tag wise2c/yum-repo:v1.19.8 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.19.8
    - docker tag wise2c/yum-repo:v1.18.16 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.16
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.20.4
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.19.8
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.16

    - docker pull wise2c/apt-source:v1.20.4
    - docker pull wise2c/apt-source:v1.19.8
    - docker pull wise2c/apt-source:v1.18.16
    - docker tag wise2c/apt-source:v1.20.4 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.20.4
    - docker tag wise2c/apt-source:v1.19.8 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.19.8
    - docker tag wise2c/apt-source:v1.18.16 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.16
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.20.4
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.19.8
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.16

  when: always
