build_image:
  image: docker:git
  services:
    - docker:dind
  script:
    - docker pull wise2c/playbook:v1.20
    - docker pull wise2c/playbook:v1.19
    - docker pull wise2c/playbook:v1.18
    - docker pull wise2c/playbook:v1.17

    - docker tag wise2c/playbook:v1.20 wise2c/playbook:v1.20.1
    - docker tag wise2c/playbook:v1.19 wise2c/playbook:v1.19.6
    - docker tag wise2c/playbook:v1.18 wise2c/playbook:v1.18.14
    - docker tag wise2c/playbook:v1.17 wise2c/playbook:v1.17.16

    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

    - docker push wise2c/playbook:v1.20.1
    - docker push wise2c/playbook:v1.19.6
    - docker push wise2c/playbook:v1.18.14
    - docker push wise2c/playbook:v1.17.16

    - docker tag wise2c/playbook:v1.20 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.20.1
    - docker tag wise2c/playbook:v1.19 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.19.6
    - docker tag wise2c/playbook:v1.18 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.14
    - docker tag wise2c/playbook:v1.17 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.16

    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com

    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.20.1
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.19.6
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.14
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.16
  when: always
