build_image:
  image: docker:git
  services:
    - docker:dind
  script:
    - wget https://github.com/vmware-tanzu/sonobuoy/releases/download/v0.50.0/sonobuoy_0.50.0_linux_amd64.tar.gz
    - tar zxvf sonobuoy_0.50.0_linux_amd64.tar.gz
    - bash sonobuoy images pull
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  when: always
