build_image:
  image: docker:git
  services:
    - docker:dind
  script:
    - docker pull wise2c/playbook:v1.20
    - docker pull wise2c/playbook:v1.19
    - docker pull wise2c/playbook:v1.18
    - docker tag wise2c/playbook:v1.20 wise2c/playbook:v1.20.5
    - docker tag wise2c/playbook:v1.19 wise2c/playbook:v1.19.9
    - docker tag wise2c/playbook:v1.18 wise2c/playbook:v1.18.17
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker push wise2c/playbook:v1.20.5
    - docker push wise2c/playbook:v1.19.9
    - docker push wise2c/playbook:v1.18.17
  when: always
