build_image:
  image: docker:git
  services:
    - docker:dind
  script:
#    - docker pull wise2c/yum-repo:v1.20.2
#    - docker pull wise2c/yum-repo:v1.19.7
#    - docker pull wise2c/yum-repo:v1.18.15
#    - docker pull wise2c/yum-repo:v1.17.17
#    - docker tag wise2c/yum-repo:v1.20.2 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.20.2
#    - docker tag wise2c/yum-repo:v1.19.7 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.19.7
#    - docker tag wise2c/yum-repo:v1.18.15 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.15
#    - docker tag wise2c/yum-repo:v1.17.17 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.17
#    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
#    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.20.2
#    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.19.7
#    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.15
#    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.17

#    - docker pull wise2c/apt-source:v1.20.2
#    - docker pull wise2c/apt-source:v1.19.7
#    - docker pull wise2c/apt-source:v1.18.15
#    - docker pull wise2c/apt-source:v1.17.17
#    - docker tag wise2c/apt-source:v1.20.2 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.20.2
#    - docker tag wise2c/apt-source:v1.19.7 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.19.7
#    - docker tag wise2c/apt-source:v1.18.15 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.15
#    - docker tag wise2c/apt-source:v1.17.17 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.17
#    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
#    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.20.2
#    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.19.7
#    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.15
#    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.17

    - docker pull wise2c/playbook:v1.20
    - docker pull wise2c/playbook:v1.19
    - docker pull wise2c/playbook:v1.18
    - docker pull wise2c/playbook:v1.17
    - docker tag wise2c/playbook:v1.20 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.20.2
    - docker tag wise2c/playbook:v1.19 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.19.7
    - docker tag wise2c/playbook:v1.18 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.15
    - docker tag wise2c/playbook:v1.17 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.17
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.20.2
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.19.7
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.15
    - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.17
  when: always
