sudo: required

services:
- docker

script:
- docker pull wise2c/playbook:${TRAVIS_BRANCH}
- docker tag wise2c/playbook:${TRAVIS_BRANCH} registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:${TRAVIS_BRANCH}
- docker pull wise2c/yum-repo:${TRAVIS_BRANCH}
- docker tag wise2c/yum-repo:${TRAVIS_BRANCH} registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:${TRAVIS_BRANCH}
- docker pull wise2c/apt-source:${TRAVIS_BRANCH}
- docker tag wise2c/apt-source:${TRAVIS_BRANCH} registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:${TRAVIS_BRANCH}
- docker pull wise2c/deploy-ui:v1.8
- docker tag wise2c/deploy-ui:v1.8 registry.cn-shenzhen.aliyuncs.com/breeze-project/deploy-ui:v1.8
- docker pull wise2c/pagoda:v1.2.0
- docker tag wise2c/pagoda:v1.2.0 registry.cn-shenzhen.aliyuncs.com/breeze-project/pagoda:v1.2.0



deploy:
  provider: script
  script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:${TRAVIS_BRANCH}
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:${TRAVIS_BRANCH}
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:${TRAVIS_BRANCH}
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/deploy-ui:v1.8
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/pagoda:v1.2.0
    on:
      all_branches: true
