sudo: required

services:
- docker

before_install:
- while sleep 5m; do echo "=====[ $SECONDS seconds, still processing... ]====="; done &

jobs:
  script:
  - docker pull wise2c/yum-repo:v1.19.4
  - docker pull wise2c/yum-repo:v1.18.12
  - docker pull wise2c/yum-repo:v1.17.14
  - docker tag wise2c/yum-repo:v1.19.4 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.19.4
  - docker tag wise2c/yum-repo:v1.18.12 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.12
  - docker tag wise2c/yum-repo:v1.17.14 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.14
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.19.4
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.12
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.14

  - docker pull wise2c/playbook:v1.19.4
  - docker pull wise2c/playbook:v1.18.12
  - docker pull wise2c/playbook:v1.17.14
  - docker tag wise2c/playbook:v1.19.4 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.19.4
  - docker tag wise2c/playbook:v1.18.12 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.12
  - docker tag wise2c/playbook:v1.17.14 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.14
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.19.4
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.12
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.14

  - docker pull wise2c/apt-source:v1.19.4
  - docker pull wise2c/apt-source:v1.18.12
  - docker pull wise2c/apt-source:v1.17.14
  - docker tag wise2c/apt-source:v1.19.4 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.19.4
  - docker tag wise2c/apt-source:v1.18.12 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.12
  - docker tag wise2c/apt-source:v1.17.14 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.14
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.19.4
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.12
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.14
