sudo: required

services:
- docker

before_install:
- while sleep 5m; do echo "=====[ $SECONDS seconds, still processing... ]====="; done &

jobs:
  script:
  - docker pull wise2c/yum-repo:v1.16.9
  - docker pull wise2c/yum-repo:v1.17.5
  - docker pull wise2c/yum-repo:v1.18.2
  - docker tag wise2c/yum-repo:v1.16.9 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.16.9
  - docker tag wise2c/yum-repo:v1.17.5 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.5
  - docker tag wise2c/yum-repo:v1.18.2 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.2
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.16.9
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.5
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.2
  - docker pull wise2c/apt-source:v1.16.9
  - docker pull wise2c/apt-source:v1.17.5
  - docker pull wise2c/apt-source:v1.18.2
  - docker tag wise2c/apt-source:v1.16.9 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.16.9
  - docker tag wise2c/apt-source:v1.17.5 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.5
  - docker tag wise2c/apt-source:v1.18.2 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.2
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.16.9
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.5
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.2
