sudo: required

services:
- docker

before_install:
- while sleep 5m; do echo "=====[ $SECONDS seconds, still processing... ]====="; done &

jobs:
  script:
  - docker pull wise2c/yum-repo:v1.19.3
  #- docker pull wise2c/yum-repo:v1.18.9
  #- docker pull wise2c/yum-repo:v1.17.12
  #- docker pull wise2c/yum-repo:v1.16.15
  - docker tag wise2c/yum-repo:v1.19.3 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.19.3
  #- docker tag wise2c/yum-repo:v1.18.9 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.9
  #- docker tag wise2c/yum-repo:v1.17.12 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.12
  #- docker tag wise2c/yum-repo:v1.16.15 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.16.15
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.19.3
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.9
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.12
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.16.15

  - docker pull wise2c/playbook:v1.19.3
  #- docker pull wise2c/playbook:v1.18.9
  #- docker pull wise2c/playbook:v1.17.12
  #- docker pull wise2c/playbook:v1.16.15
  - docker tag wise2c/playbook:v1.19.3 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.19.3
  #- docker tag wise2c/playbook:v1.18.9 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.9
  #- docker tag wise2c/playbook:v1.17.12 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.12
  #- docker tag wise2c/playbook:v1.16.15 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.16.15
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.19.3
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.9
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.12
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.16.15

  - docker pull wise2c/apt-source:v1.19.3
  #- docker pull wise2c/apt-source:v1.18.9
  #- docker pull wise2c/apt-source:v1.17.12
  #- docker pull wise2c/apt-source:v1.16.15
  - docker tag wise2c/apt-source:v1.19.3 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.19.3
  #- docker tag wise2c/apt-source:v1.18.9 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.9
  #- docker tag wise2c/apt-source:v1.17.12 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.12
  #- docker tag wise2c/apt-source:v1.16.15 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.16.15
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.19.3
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.9
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.12
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.16.15
