sudo: required

services:
- docker

before_install:
- while sleep 5m; do echo "=====[ $SECONDS seconds, still processing... ]====="; done &

jobs:
  script:
  - docker pull wise2c/yum-repo:master
  - docker pull wise2c/yum-repo:v1.18.5
  - docker pull wise2c/yum-repo:v1.17.8
  - docker pull wise2c/yum-repo:v1.16.12
  - docker tag wise2c/yum-repo:master registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:master
  - docker tag wise2c/yum-repo:v1.18.5 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.5
  - docker tag wise2c/yum-repo:v1.17.8 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.8
  - docker tag wise2c/yum-repo:v1.16.12 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.16.12
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.5
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.8
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.16.12

  #- docker pull wise2c/playbook:v1.18
  #- docker pull wise2c/playbook:v1.17
  #- docker pull wise2c/playbook:v1.16
  #- docker tag wise2c/playbook:v1.18 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.5
  #- docker tag wise2c/playbook:v1.17 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.8
  #- docker tag wise2c/playbook:v1.16 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.16.12
  #- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.4
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.7
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.16.11

  - docker pull wise2c/apt-source:v1.18.5
  - docker pull wise2c/apt-source:v1.17.8
  - docker pull wise2c/apt-source:v1.16.12
  - docker tag wise2c/apt-source:v1.18.5 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.5
  - docker tag wise2c/apt-source:v1.17.8 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.8
  - docker tag wise2c/apt-source:v1.16.12 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.16.12
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.5
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.8
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.16.12
