sudo: required

services:
- docker

before_install:
- while sleep 5m; do echo "=====[ $SECONDS seconds, still processing... ]====="; done &

jobs:
  script:
  #- docker pull wise2c/yum-repo:v1.16.10
  #- docker pull wise2c/yum-repo:v1.17.6
  #- docker pull wise2c/yum-repo:v1.18.3
  #- docker tag wise2c/yum-repo:v1.16.10 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.16.10
  #- docker tag wise2c/yum-repo:v1.17.6 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.6
  #- docker tag wise2c/yum-repo:v1.18.3 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.3
  #- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.16.10
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.6
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.3

  - docker pull wise2c/playbook:v1.16.10
  - docker pull wise2c/playbook:v1.17.6
  - docker pull wise2c/playbook:v1.18
  - docker tag wise2c/playbook:v1.16.10 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.16.10
  - docker tag wise2c/playbook:v1.17.6 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.6
  - docker tag wise2c/playbook:v1.18 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.3
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.16.10
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.6
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.3

  #- docker pull wise2c/apt-source:v1.16.10
  #- docker pull wise2c/apt-source:v1.17.6
  #- docker pull wise2c/apt-source:v1.18.3
  #- docker tag wise2c/apt-source:v1.16.10 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.16.10
  #- docker tag wise2c/apt-source:v1.17.6 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.6
  #- docker tag wise2c/apt-source:v1.18.3 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.3
  #- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.16.10
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.6
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.3
