sudo: required

services:
- docker

before_install:
- while sleep 5m; do echo "=====[ $SECONDS seconds, still processing... ]====="; done &

jobs:
  script:
  #- docker pull wise2c/yum-repo:v1.18.4
  #- docker pull wise2c/yum-repo:v1.17.7
  #- docker pull wise2c/yum-repo:v1.16.11
  #- docker tag wise2c/yum-repo:v1.18.4 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.4
  #- docker tag wise2c/yum-repo:v1.17.7 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.7
  #- docker tag wise2c/yum-repo:v1.16.11 registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.16.11
  #- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.18.4
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.17.7
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/yum-repo:v1.16.11

  - docker pull wise2c/playbook:v1.18
  - docker pull wise2c/playbook:v1.17
  - docker pull wise2c/playbook:v1.16
  - docker tag wise2c/playbook:v1.18 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.4
  - docker tag wise2c/playbook:v1.17 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.7
  - docker tag wise2c/playbook:v1.16 registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.16.11
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.18.4
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.17.7
  - docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/playbook:v1.16.11

  #- docker pull wise2c/apt-source:v1.18.4
  #- docker pull wise2c/apt-source:v1.17.7
  #- docker pull wise2c/apt-source:v1.16.11
  #- docker tag wise2c/apt-source:v1.18.4 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.4
  #- docker tag wise2c/apt-source:v1.17.7 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.7
  #- docker tag wise2c/apt-source:v1.16.11 registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.16.11
  #- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.18.4
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.17.7
  #- docker push registry.cn-shenzhen.aliyuncs.com/breeze-project/apt-source:v1.16.11
